[project]
name = "robot-learning"
version = "0.1.0"
description = "Add description here"
requires-python = ">=3.9"

dependencies = [
    "robosuite",
    "tensorboard>=2.20.0",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]

[tool.uv.sources]
robosuite = { path = "./robosuite" }
