[project]
name = "robot-learning"
version = "0.1.0"
description = "Add description here"
requires-python = ">=3.9"

dependencies = [
    "matplotlib>=3.9.4",
    "tensorboard>=2.20.0",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]
